if (Meteor.users.find().count() == 0) {
    var a = Accounts.createUser({username: "EPutin", password:"123456", email:"Put@gmx.de"})
    var b = Accounts.createUser({username: "HMeier", password:"123456", email:"dafuqington@gmail.com"})
    var c = Accounts.createUser({username: "PSchlau", password:"123456", email:"oh@hai.de"})
    var d = Accounts.createUser({username: "BMaja", password:"123456", email:"biene@maja.net"})
    Meteor.users.update({username : "ESchoeneberg"}, {$set: {hours: 39}})
    Meteor.users.update({username : "HMeier"}, {$set: {hours: 38}})
    Meteor.users.update({username : "PSchlau"}, {$set: {hours: 38}})
    Meteor.users.update({username : "BMaja"}, {$set: {hours: 38}})
    Roles.addUsersToRoles(a, "3", "group")
    Roles.addUsersToRoles(b, "2", "group")
    Roles.addUsersToRoles(c, "2", "group")
    Roles.addUsersToRoles(d, "AG", "group")
    var f = Schedules.insert({year: 2014, month: 2, group: "3"})
    Times.insert({user: a, schedule: f, startTime: new Date(2014, 1, 2, 13), endTime: new Date(2014, 1, 2, 15)})
    Times.insert({user: a, schedule: f, startTime: new Date(2014, 1, 4, 13), endTime: new Date(2014, 1, 4, 15)})
}